### ISSUE TITLE
Create binding that provides a new instance of a controller for each request

### ISSUE THREAD

**Issue by tomwaterhouse** [scaldi/scaldi-play#9] opened 2015-02-11 00:42 UTC
It appears to me that the existing Play binding is to a singleton instance. I have a use case in which a new controller instance is required, and with the existing binding the same controller instance is used for each request.

This would be equivalent to having a 'toProvider' option for controller injections.

**Comment by OlegIlyenko** [comment] 2015-02-11 01:17
In general I would discourage from doing this because of the performance concerns. It can be pretty expensive operation to lookup the controller on each requests. So most web frameworks cache them. As far as I'm aware this is also the same concern with other DI libraries like guice.

But if you have a valid use-case and some performance trade-off is acceptable, then I guess it should be fine. In theory you can define an explicit binding bound with `toProvider` just for this controller. This will override any auto-discovered binding that may come from the `ControllerInjector` (`ControllerInjector` would not even be used for this controller). But the problem is that scaldi-play also uses cache for all of the controllers. 

You can easily solve this fro your case by overriding `getControllerInstance` in your app's `Global`:

https://github.com/scaldi/scaldi-play/blob/master/src/main/scala/scaldi/play/ScaldiSupport.scala#L80

You can implement it the way `getBoundInstance` is implemented, or you avoid cache only for some of the controllers and delegate the rest to `super`.

For the next version of scaldi-play I will definitely think how this concept can be implemented. When i added `ControllerInjector` I had idea to store information on binding - whether it can be cachable or not. Many interesting caching mechanisms can profit greatly from this. But at that moment I haven't implemented this kind of mechanism. I think it's a good candidate for the next release of scaldi itself (which of course will also influence caching in scaldi-play). I created an issue for this: https://github.com/scaldi/scaldi/issues/45

**Comment by tomwaterhouse** [comment] 2015-02-11 17:06
My use case for this request is a data access object that is unfortunately stateful.  Its binding is implemented using 'toProvider', returning a new instance each injection.  The service that uses the data access object is also required to be bound with 'toProvider'.  The controller in question uses the service.

The work-around I used is to use a getter method in the controller for the service. The injection of the service instance is then done each access, and a new instance of the service is created each time.

**Comment by OlegIlyenko** [comment] 2015-04-11 15:51
Fixed in **v0.5.4**. Controllers that are bound with `toProvider` will not be cached anymore.

http://scaldi.org/learn/#controller-cache

**Closed by OlegIlyenko** 2015-04-11 15:51 UTC
Labels: enhancement
